import React,{ useState,useEffect } from 'react';
import { useNavigate } from 'react-router-dom';

import {
  Button,
  Col,
  Row,
} from 'reactstrap';


import ComponentCard from '../../../components/ComponentCard';

const BomCoding = () => {
  const navigate = useNavigate();
  const [data, setData] = useState([
    { id: 1, BomCodingName: 'Apparel', CategoryCode: 'APP' ,SerialNumber:1},
    { id: 2, BomCodingName: 'Automotive', CategoryCode: 'AUT' ,SerialNumber:2},
    { id: 3, BomCodingName: 'Eco Material', CategoryCode: 'ECO',SerialNumber:3 },
    { id: 4, BomCodingName: 'Flooring', CategoryCode: 'FLO',SerialNumber:4 },
    { id: 5, BomCodingName: 'Foams', CategoryCode: 'FOM',SerialNumber:5 },
    { id: 6, BomCodingName: 'Footwear', CategoryCode: 'FOT',SerialNumber:6 },
    { id: 7, BomCodingName: 'Leathergoods', CategoryCode: 'LET',SerialNumber:7 },
    { id: 8, BomCodingName: 'Saddlery', CategoryCode: 'SAD' ,SerialNumber:8},
    { id: 9, BomCodingName: 'Upholstery', CategoryCode: 'UPH',SerialNumber:9 },
    { id: 10, BomCodingName: 'WINNER', CategoryCode: 'WIN',SerialNumber:10 },
  ]);
  // const data = [
  //   { id: 1, BomCodingName: 'Apparel', CategoryCode: 'APP' },
  //   { id: 2, BomCodingName: 'Automotive', CategoryCode: 'AUT' },
  //   { id: 3, BomCodingName: 'Eco Material', CategoryCode: 'ECO' },
  //   { id: 4, BomCodingName: 'Flooring', CategoryCode: 'FLO' },
  //   { id: 5, BomCodingName: 'Foams', CategoryCode: 'FOM' },
  //   { id: 6, BomCodingName: 'Footwear', CategoryCode: 'FOT' },
  //   { id: 7, BomCodingName: 'Leathergoods', CategoryCode: 'LET' },
  //   { id: 8, BomCodingName: 'Saddlery', CategoryCode: 'SAD' },
  //   { id: 9, BomCodingName: 'Upholstery', CategoryCode: 'UPH' },
  //   { id: 10, BomCodingName: 'WINNER', CategoryCode: 'WIN' },
  // ];
  
  const tableStyle = {
    // margin: 'auto', 
    // width: '60%',  
    // maxWidth: '1000px',
  };
  const handleEditClick = (item) => {
    // Navigate to the edit page with the item's id
    // Navigate(`/resources/address-types/edit/${itemId}`);
    navigate('/resources/bom-coding-category/edit', { state: item });
  };

  const handleEditAdd = () => {
    // Navigate to the edit page with the item's id
    // Navigate(`/resources/address-types/edit/${itemId}`);
    navigate('/resources/bom-coding-category/add');
  };

  const handleDeleteClick = async (itemId) => {
    try {
      // Call your API endpoint to delete the item
      // const response = await fetch(`your-api-endpoint/${itemId}`, {
      //   method: 'DELETE',
      //   headers: {
      //     // Your headers here (if needed)
      //   }
      // });
  
      // Check if the request was successful
      // if (!response.ok) {
      //   throw new Error(`Error: ${response.statusText}`);
      // }
  
      // Filter out the deleted item from your data state
      const updatedData = data.filter((item) => item.id !== itemId);
      setData(updatedData);
  
      console.log('Item deleted successfully');
    } catch (error) {
      //only checks for error that are generated by fetch function , and cors 
      console.error('Failed to delete the item', error);
    }
  };
  

  useEffect(() => {
    
    // Fetch the data from the API
    const fetchData = async () => {
      const token = localStorage.getItem('userToken');
      console.log('token',token);
      const response = await fetch('https://indiapuleather.com/teamasia/api/public/cities', {
        method: 'GET', 
        headers: {
          'Authorization': `Bearer ${token}`
        }
      });
      console.log('result',response);
      if (!response.ok) {
        throw new Error(`HTTP error! status: ${response.status}`);
      }
      const result = await response.json();
      setData(result); 
    };
  
    fetchData();
  }, []);

  return (
    <ComponentCard
    title=""
    subtitle={
      <p>
        {/* Overview of the projects */}
      </p>
    }
  >
     <Row>
      <Col md="8">
        <Button className='my-btn-color' style={{ marginBottom: '1rem',marginRight:'10px' }} onClick={() => handleEditAdd()}>
          Add BOM Coding Category Master
        </Button>
      </Col>
    </Row>

    <div style={{ display: 'flex', justifyContent: 'center', alignItems: 'center', height: '100%' }}>
      <table className="table" style={tableStyle}>
              <thead>
              <tr>
            <th>#</th>
            <th>Bom Coding Name</th>
            <th>Category Code</th>
            <th>Actions</th>
          </tr>
              </thead>
              <tbody>
                {data.map((product) => (
                  <tr key={product.id}>
                  <td>{product.id}</td>
                  <td>{product.BomCodingName}</td>
                  <td>{product.CategoryCode}</td>
                  <td>
                    {/* Action buttons or icons */}
                      <button type="button" className="btn mybtncustomer btn-secondary btn-sm mr-2" onClick={() => handleEditClick(product)}><i className="bi bi-pencil-fill my-pen-color" /></button>
                      <button type="button" className="btn mybtncustomer btn-secondary btn-sm mr-2" onClick={() => handleDeleteClick(product.id)}><i className="bi bi-trash-fill my-trash-color" /></button>
                  </td>
                </tr>
                ))}
              </tbody>
            </table>
            
    </div>
   
  </ComponentCard>

   
   
  );
};

export default BomCoding;