import React,{ useState,useEffect } from 'react';
import { useNavigate } from 'react-router-dom';

import {
  Button,
  Col,
  Row,
} from 'reactstrap';
import ComponentCard from '../../../components/ComponentCard';

const Cities = () => {
  const navigate = useNavigate();
  const [data, setData] = useState([]);
  const [data2, setData2] = useState([]);
  const [data3, setData3] = useState([]);

  // const data2 = [
  //   { id: 1, CityName: 'Noida', State: 'Uttar Pradesh', Country: 'India' },
  //   { id: 2, CityName: 'Noida', State: 'Uttar Pradesh', Country: 'India' },
  //   { id: 3, CityName: 'Noida', State: 'Uttar Pradesh', Country: 'India' },
  //   { id: 4, CityName: 'Noida', State: 'Uttar Pradesh', Country: 'India' },
  //   { id: 5, CityName: 'Noida', State: 'Uttar Pradesh', Country: 'India' },
  //   { id: 6, CityName: 'Noida', State: 'Uttar Pradesh', Country: 'India' },
  //   { id: 7, CityName: 'Noida', State: 'Uttar Pradesh', Country: 'India' },
  //   { id: 8, CityName: 'Noida', State: 'Uttar Pradesh', Country: 'India' },
  //   { id: 9, CityName: 'Noida', State: 'Uttar Pradesh', Country: 'India' },
  //   { id: 10, CityName: 'Noida', State: 'Uttar Pradesh', Country: 'India' },
  // ];
  
  const tableStyle = {
    // margin: 'auto', 
    // width: '60%',  
    // maxWidth: '1000px',
  };
  const handleEditClick = (item) => {
    // Navigate to the edit page with the item's id
    // Navigate(`/resources/address-types/edit/${itemId}`);
    navigate('/resources/cities/edit', { state: item });
  };
  const handleEditAdd = () => {
    // Navigate to the edit page with the item's id
    // Navigate(`/resources/address-types/edit/${itemId}`);
    navigate('/resources/cities/add');
  };
  const handleDeleteClick = async (itemId) => {
    try {
      // Call your API endpoint to delete the item
      const token = localStorage.getItem('userToken');
      const response = await fetch(`https://factory.teamasia.in/api/public/cities/${itemId}`, {
        method: 'DELETE',
        headers: {
          'Authorization': `Bearer ${token}`
        }
      });
  
      // Check if the request was successful
      if (!response.ok) {
        throw new Error(`Error: ${response.statusText}`);
      }
  
      // Filter out the deleted item from your data state
      const updatedData = data.filter((item) => item.id !== itemId);
      setData(updatedData);
  
      console.log('Item deleted successfully');
    } catch (error) {
      //only checks for error that are generated by fetch function , and cors 
      console.error('Failed to delete the item', error);
    }
  };
  
  function getStateNameById(stateId) {
    const stateName = data3.find(state => state.id === stateId);
    console.log('state',stateName);
    return stateName ? stateName.name : 'Unknown State';
  }
  
  // This function finds the name of the country by its ID
  function getCountryNameById(countryId) {
    const countryName = data2.find(country => country.id === countryId);
    console.log('country',countryName);
    return countryName ? countryName.name : 'Unknown Country';
  }

  const citiesWithNames = data.map(city => ({
    ...city,
    stateName: getStateNameById(city.state_id),
    countryName: getCountryNameById(city.country_id)
  }));

  useEffect(() => {
    
    // Fetch the data from the API
    const fetchData = async () => {
      const token = localStorage.getItem('userToken');
      // console.log('token',token);
      const response = await fetch('https://factory.teamasia.in/api/public/cities', {
        method: 'GET', 
        headers: {
          'Authorization': `Bearer ${token}`
        }
      });
      // console.log('result',response);
      if (!response.ok) {
        throw new Error(`HTTP error! status: ${response.status}`);
      }
      const result = await response.json();
      console.log("responsejson",result);
      setData(result.cities); 
    };

    const fetchData2 = async () => {
      const token = localStorage.getItem('userToken');
      // console.log('token',token);
      const response = await fetch('https://factory.teamasia.in/api/public/countries', {
        method: 'GET', 
        headers: {
          'Authorization': `Bearer ${token}`
        }
      });
      // console.log('result',response);
      if (!response.ok) {
        throw new Error(`HTTP error! status: ${response.status}`);
      }
      const result = await response.json();
      console.log("responsejson2",result);
      setData2(result.countries); 
    };
    const fetchData3 = async () => {
      const token = localStorage.getItem('userToken');
      // console.log('token',token);
      const response = await fetch('https://factory.teamasia.in/api/public/states', {
        method: 'GET', 
        headers: {
          'Authorization': `Bearer ${token}`
        }
      });
      // console.log('result',response);
      if (!response.ok) {
        throw new Error(`HTTP error! status: ${response.status}`);
      }
      const result = await response.json();
      console.log("responsejson3",result);
      setData3(result.states); 
    };
  
    fetchData3();
    fetchData2();
    fetchData();

  
  },[]);

  return (
    <ComponentCard
    title=""
    subtitle={
      <p>
        {/* Overview of the projects */}
      </p>
    }
  >
     <Row>
      <Col md="8">
        <Button className='my-btn-color' style={{ marginBottom: '1rem',marginRight:'10px' }} onClick={() => handleEditAdd()}>
          Add City
        </Button>
      </Col>
    </Row>

    <div style={{ display: 'flex', justifyContent: 'center', alignItems: 'center', height: '100%' }}>
      <table className="table" style={tableStyle}>
              <thead>
              <tr>

            <th>City Name</th>
            <th>State</th>
            <th>Country</th>
            <th>Actions</th>
          </tr>
              </thead>
              <tbody>
                {citiesWithNames.map((product) => (
                  <tr key={product.id}>
                  <td>{product.name}</td>
                  <td>{product.stateName}</td>
                  <td>{product.countryName}</td>
                  <td>
                      <button type="button" className="btn mybtncustomer btn-secondary btn-sm mr-2" onClick={() => handleEditClick(product)}><i className="bi bi-pencil-fill my-pen-color" /></button>
                      <button type="button" className="btn mybtncustomer btn-secondary btn-sm mr-2" onClick={() => handleDeleteClick(product.id)}><i className="bi bi-trash-fill my-trash-color" /></button>
                  </td>
                </tr>
                ))}

     
              </tbody>
            </table>
            
    </div>
   
  </ComponentCard>

   
   
  );
};

export default Cities;