import React,{ useState,useEffect } from 'react';
import { useNavigate } from 'react-router-dom';

import {
  Button,
  Col,
  Row,
} from 'reactstrap';
import ComponentCard from '../../../components/ComponentCard';

const Cities = () => {
  const navigate = useNavigate();
  const [data, setData] = useState([
    { id: 1, CityName: 'Noida', State: 'Uttar Pradesh', Country: 'India' },
    { id: 2, CityName: 'Noida1', State: 'Uttar Pradesh1', Country: 'India1' },
    { id: 3, CityName: 'Noida2', State: 'Uttar Pradesh2', Country: 'India2' },
    { id: 4, CityName: 'Noida3', State: 'Uttar Pradesh3', Country: 'India3' },
    { id: 5, CityName: 'Noida4', State: 'Uttar Pradesh4', Country: 'India4' },
    { id: 6, CityName: 'Noida5', State: 'Uttar Pradesh5', Country: 'India5' },
    { id: 7, CityName: 'Noida6', State: 'Uttar Pradesh6', Country: 'India6' },
    { id: 8, CityName: 'Noida7', State: 'Uttar Pradesh7', Country: 'India7' },
    { id: 9, CityName: 'Noida8', State: 'Uttar Pradesh8', Country: 'India8' },
    { id: 10, CityName: 'Noida9', State: 'Uttar Pradesh9', Country: 'India9' },
  ]);

  // const data = [
  //   { id: 1, CityName: 'Noida', State: 'Uttar Pradesh', Country: 'India' },
  //   { id: 2, CityName: 'Noida', State: 'Uttar Pradesh', Country: 'India' },
  //   { id: 3, CityName: 'Noida', State: 'Uttar Pradesh', Country: 'India' },
  //   { id: 4, CityName: 'Noida', State: 'Uttar Pradesh', Country: 'India' },
  //   { id: 5, CityName: 'Noida', State: 'Uttar Pradesh', Country: 'India' },
  //   { id: 6, CityName: 'Noida', State: 'Uttar Pradesh', Country: 'India' },
  //   { id: 7, CityName: 'Noida', State: 'Uttar Pradesh', Country: 'India' },
  //   { id: 8, CityName: 'Noida', State: 'Uttar Pradesh', Country: 'India' },
  //   { id: 9, CityName: 'Noida', State: 'Uttar Pradesh', Country: 'India' },
  //   { id: 10, CityName: 'Noida', State: 'Uttar Pradesh', Country: 'India' },
  // ];
  
  const tableStyle = {
    // margin: 'auto', 
    // width: '60%',  
    // maxWidth: '1000px',
  };
  const handleEditClick = (item) => {
    // Navigate to the edit page with the item's id
    // Navigate(`/resources/address-types/edit/${itemId}`);
    navigate('/resources/cities/edit', { state: item });
  };
  const handleEditAdd = () => {
    // Navigate to the edit page with the item's id
    // Navigate(`/resources/address-types/edit/${itemId}`);
    navigate('/resources/cities/add');
  };
  const handleDeleteClick = async (itemId) => {
    try {
      // Call your API endpoint to delete the item
      // const response = await fetch(`your-api-endpoint/${itemId}`, {
      //   method: 'DELETE',
      //   headers: {
      //     // Your headers here (if needed)
      //   }
      // });
  
      // Check if the request was successful
      // if (!response.ok) {
      //   throw new Error(`Error: ${response.statusText}`);
      // }
  
      // Filter out the deleted item from your data state
      const updatedData = data.filter((item) => item.id !== itemId);
      setData(updatedData);
  
      console.log('Item deleted successfully');
    } catch (error) {
      //only checks for error that are generated by fetch function , and cors 
      console.error('Failed to delete the item', error);
    }
  };
  

  useEffect(() => {
    
    // Fetch the data from the API
    const fetchData = async () => {
      const token = localStorage.getItem('userToken');
      console.log('token',token);
      const response = await fetch('https://indiapuleather.com/teamasia/api/public/cities', {
        method: 'GET', 
        headers: {
          'Authorization': `Bearer ${token}`
        }
      });
      console.log('result',response);
      if (!response.ok) {
        throw new Error(`HTTP error! status: ${response.status}`);
      }
      const result = await response.json();
      setData(result); 
    };
  
    fetchData();
  }, []);

  return (
    <ComponentCard
    title=""
    subtitle={
      <p>
        {/* Overview of the projects */}
      </p>
    }
  >
     <Row>
      <Col md="8">
        <Button className='my-btn-color' style={{ marginBottom: '1rem',marginRight:'10px' }} onClick={() => handleEditAdd()}>
          Add City
        </Button>
      </Col>
    </Row>

    <div style={{ display: 'flex', justifyContent: 'center', alignItems: 'center', height: '100%' }}>
      <table className="table" style={tableStyle}>
              <thead>
              <tr>

            <th>City Name</th>
            <th>State</th>
            <th>Country</th>
            <th>Actions</th>
          </tr>
              </thead>
              <tbody>
                {data.map((product) => (
                  <tr key={product.id}>
                  <td>{product.CityName}</td>
                  <td>{product.State}</td>
                  <td>{product.Country}</td>
                  <td>
                    {/* Action buttons or icons */}
                      <button type="button" className="btn mybtncustomer btn-secondary btn-sm mr-2" onClick={() => handleEditClick(product)}><i className="bi bi-pencil-fill my-pen-color" /></button>
                      <button type="button" className="btn mybtncustomer btn-secondary btn-sm mr-2" onClick={() => handleDeleteClick(product.id)}><i className="bi bi-trash-fill my-trash-color" /></button>
                  </td>
                </tr>
                ))}
              </tbody>
            </table>
            
    </div>
   
  </ComponentCard>

   
   
  );
};

export default Cities;