import React ,{useState,useEffect} from 'react';
import {
  Table,
  Button,
  Col,
  Row,
} from 'reactstrap';

import { useNavigate } from 'react-router-dom';
import ComponentCard from '../../components/ComponentCard';

const User = () => {
  const [data, setData] = useState([]);

  const navigate = useNavigate();
  // const data = [
  //   { id: 1, Name: '1037 A', Email: 'sonu.modal@teamcolence.com', Mobile: '9315496801', Role: 'superadmin', Mfastatus: 'Disable'},
  //   { id: 2, Name: '1037 A', Email: 'sonu.modal@teamcolence.com', Mobile: '9315496801', Role: 'Admin', Mfastatus: 'Disable'},
  //   { id: 3, Name: '1037 A', Email: 'sonu.modal@teamcolence.com', Mobile: '9315496801', Role: 'Admin', Mfastatus: 'Disable'},
  //   { id: 4, Name: '1037 A', Email: 'sonu.modal@teamcolence.com', Mobile: '9315496801', Role: 'Admin', Mfastatus: 'Disable'},
  //   { id: 5, Name: '1037 A', Email: 'sonu.modal@teamcolence.com', Mobile: '9315496801', Role: 'Admin', Mfastatus: 'Disable'},
  //   { id: 6, Name: '1037 A', Email: 'sonu.modal@teamcolence.com', Mobile: '9315496801', Role: 'Admin', Mfastatus: 'Disable'},
  //   { id: 7, Name: '1037 A', Email: 'sonu.modal@teamcolence.com', Mobile: '9315496801', Role: 'Admin', Mfastatus: 'Disable'},
  //   { id: 8, Name: '1037 A', Email: 'sonu.modal@teamcolence.com', Mobile: '9315496801', Role: 'Admin', Mfastatus: 'Disable'},
  //   { id: 9, Name: '1037 A', Email: 'sonu.modal@teamcolence.com', Mobile: '9315496801', Role: 'Admin', Mfastatus: 'Disable'},
  //   { id: 10, Name: '1037 A', Email: 'sonu.modal@teamcolence.com', Mobile: '9315496801', Role: 'Admin', Mfastatus: 'Disable'},
  // ];
 
  const handleEditClick = (item) => {
    // Navigate to the edit page with the item's id
    // Navigate(`/resources/address-types/edit/${itemId}`);
    navigate('/users/edit', { state: item });
  };

  const handleEditAdd = () => {
    // Navigate to the edit page with the item's id
    // Navigate(`/resources/address-types/edit/${itemId}`);
    navigate('/users/add');
  };
  const handleDeleteClick = async (itemId) => {
    try {
      // Call your API endpoint to delete the item
      const response = await fetch(`https://factory.teamasia.in/api/public/users/${itemId}`, {
        method: 'DELETE',
        headers: {
          // Your headers here (if needed)
        }
      });
  
      // Check if the request was successful
      if (!response.ok) {
        throw new Error(`Error: ${response.statusText}`);
      }
  
      // Filter out the deleted item from your data state
      const updatedData = data.filter((item) => item.id !== itemId);
      setData(updatedData);
  
      console.log('Item deleted successfully');
    } catch (error) {
      //only checks for error that are generated by fetch function , and cors 
      console.error('Failed to delete the item', error);
    }
  };

  useEffect(() => {
    
    // Fetch the data from the API
    const fetchData = async () => {
      const token = localStorage.getItem('userToken');
      console.log('token',token);
      const response = await fetch('https://factory.teamasia.in/api/public/users?is_trashed=0', {
        method: 'GET', 
        headers: {
          'Authorization': `Bearer ${token}`
        }
      });
      console.log('result',response);
      if (!response.ok) {
        throw new Error(`HTTP error! status: ${response.status}`);
      }
      const result = await response.json();
      console.log('user',result.users)
      setData(result.users); 
    };
  
    fetchData();
  }, []);

  return (
    <ComponentCard
    title=""
    subtitle={
      <p>
        {/* Overview of the projects */}
      </p>
    }
  >
      <Row>
      <Col md="8">
        <Button className='my-btn-color' style={{ marginBottom: '1rem',marginRight:'10px' }} onClick={() => handleEditAdd()}>
          Add User
        </Button>
      </Col>
    </Row>

      <Table  responsive>
              <thead>
              <tr>

            <th>Name</th>
            <th>Email</th>
            <th>Mobile</th>
            <th>Role</th>
            <th>Mfastatus</th>
            <th>Actions</th>
          </tr>
              </thead>
              <tbody>
                {data.map((user) => (
                  <tr key={user.id}>
                  <td>{user.first_name}</td>
                  <td>{user.email}</td>
                  <td>{user.mobile}</td>
                  <td>{user.role_id}</td>
                  <td>{user.status}</td>
                  <td>
                    {/* Action buttons or icons */}
                      <button type="button" className="btn mybtncustomer btn-secondary btn-sm mr-2" onClick={() => handleEditClick(user)}><i className="bi bi-pencil-fill my-pen-color" /></button>
                      <button type="button" className="btn mybtncustomer btn-secondary btn-sm mr-2"> <i className="bi bi-shield-shaded my-eye-color" /> </button>
                      <button type="button" className="btn mybtncustomer btn-secondary btn-sm mr-2" onClick={() => handleDeleteClick(user.id)}><i className="bi bi-trash-fill my-trash-color" /></button>
                  </td>
                </tr>
                ))}
              </tbody>
            </Table>
            
   
  </ComponentCard>

   
   
  );
};

export default User;